<div class="admin-console mx-auto max-w-[1600px] space-y-6">
    <div class="flex flex-wrap items-end justify-between gap-4">
        <div><p class="admin-kicker">Control tower / live archive</p><h2 class="admin-display">Main Console</h2></div>
        <div class="text-right"><p class="text-[10px] font-bold uppercase tracking-widest text-emerald-400">● All systems operational</p><p class="mt-1 text-[9px] uppercase tracking-widest text-zinc-600">{{ now()->format('d M Y · H:i') }} UTC</p></div>
    </div>

    <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
        @foreach ([['Active readers', number_format($totalActiveUsers), 'users'], ['Total novels', number_format($totalNovels), 'books'], ['Pending requests', number_format($pendingReports), 'queue'], ['Revenue points', number_format($totalRevenuePoints), 'points']] as [$label, $value, $hint])
            <section class="console-card p-5"><div class="flex items-start justify-between"><p class="admin-kicker">{{ $label }}</p><span class="metric-icon">{{ $hint === 'users' ? '♙' : ($hint === 'books' ? '▣' : ($hint === 'queue' ? '⇧' : '◇')) }}</span></div><p class="admin-display mt-3 !text-3xl">{{ $value }}</p><p class="mt-2 text-[9px] uppercase tracking-widest" style="color:{{ $hint === 'queue' ? '#c79a42' : '#73b58c' }}">● {{ $hint === 'queue' ? 'Review required' : 'Platform overview' }}</p></section>
        @endforeach
    </div>

    <div class="grid grid-cols-1 gap-4 xl:grid-cols-12">
        <section class="console-card p-5 xl:col-span-8">
            <div class="flex items-start justify-between"><div><p class="admin-kicker">Platform activity</p><h3 class="admin-section-title">Reader engagement</h3></div><span class="text-[9px] text-zinc-500">LIVE OVERVIEW</span></div>
            <div class="mt-5 grid grid-cols-3 gap-3 border-b border-white/5 pb-5"><div><p class="admin-display !text-2xl">{{ number_format($totalActiveUsers / 1000, 1) }}k</p><p class="admin-kicker mt-1">Active readers</p></div><div><p class="admin-display !text-2xl">{{ number_format($totalNovels) }}</p><p class="admin-kicker mt-1">Published novels</p></div><div><p class="admin-display !text-2xl">{{ number_format($latestNovelUpdates->count()) }}</p><p class="admin-kicker mt-1">Recent chapters</p></div></div>
            <div class="activity-chart mt-5" aria-label="Reader engagement overview"><div class="chart-lines"></div><svg viewBox="0 0 800 180" preserveAspectRatio="none" class="h-full w-full"><path d="M0 145 C80 130 90 140 150 110 S250 128 320 88 S410 115 475 72 S570 95 635 52 S720 80 800 25" fill="none" stroke="#c7a13b" stroke-width="2.5"/><path d="M0 155 C70 150 100 128 160 132 S260 112 330 116 S410 92 480 105 S570 82 640 88 S740 58 800 48" fill="none" stroke="#53677a" stroke-width="2"/></svg></div>
            <div class="mt-2 flex justify-between text-[9px] uppercase tracking-widest text-zinc-600"><span>Catalog activity</span><span>Recent updates</span><span>Today</span></div>
        </section>
        <section class="console-card p-5 xl:col-span-4"><div class="flex items-center justify-between"><div><p class="admin-kicker">Moderation</p><h3 class="admin-section-title">Approval queue</h3></div><a class="admin-link" href="{{ route('admin.requests.index') }}">View queue →</a></div><p class="admin-display mt-5 !text-3xl">{{ number_format($pendingReports) }}</p><p class="admin-kicker mt-1">Pending reports</p><div class="mt-5 divide-y divide-white/5">@forelse($latestNovelUpdates->take(3) as $chapter)<div class="flex items-center justify-between gap-3 py-3"><div class="min-w-0"><p class="truncate font-serif text-sm text-zinc-200">{{ $chapter->novel?->title ?? $chapter->title }}</p><p class="admin-kicker mt-1">{{ $chapter->novel?->author?->name ?? 'Recent update' }}</p></div><span class="badge">NEW</span></div>@empty<p class="py-4 text-xs text-zinc-500">No recent submissions.</p>@endforelse</div></section>
    </div>

    <div class="grid grid-cols-1 gap-4 xl:grid-cols-12">
        <section class="console-card p-5 xl:col-span-8"><div class="flex items-center justify-between"><div><p class="admin-kicker">Audit stream</p><h3 class="admin-section-title">Recent global activity</h3></div><a class="admin-link" href="{{ route('admin.content-logs.index') }}">Open all logs →</a></div><div class="mt-5 overflow-x-auto"><table class="console-table w-full text-left"><thead><tr><th>Account</th><th>Role</th><th>Joined</th><th>Status</th></tr></thead><tbody>@forelse($latestUsers as $user)<tr><td>{{ $user->name }}</td><td>{{ $user->role }}</td><td>{{ $user->created_at?->diffForHumans() }}</td><td><span class="status-dot">● Active</span></td></tr>@empty<tr><td colspan="4" class="py-8 text-center text-zinc-500">No recent account activity.</td></tr>@endforelse</tbody></table></div></section>
        <section class="console-card p-5 xl:col-span-4"><div><p class="admin-kicker">Infrastructure</p><h3 class="admin-section-title">System health</h3></div><p class="admin-display mt-5 !text-3xl">Operational</p><p class="admin-kicker mt-1">Application status</p><div class="mt-5 space-y-4">@foreach(['Core application', 'Reading delivery', 'Search index'] as $service)<div><div class="flex justify-between text-xs"><span class="font-serif text-zinc-300">{{ $service }}</span><span class="text-emerald-400">Operational</span></div><div class="health-line mt-2"></div></div>@endforeach</div><a href="{{ route('admin.maintenance') }}" class="maintenance-link mt-6 block">›　Maintenance settings <span class="float-right">↗</span></a></section>
    </div>

    <div class="grid grid-cols-1 gap-4 xl:grid-cols-12"><section class="console-card p-5 xl:col-span-8"><div class="flex items-center justify-between"><div><p class="admin-kicker">Discovery operations</p><h3 class="admin-section-title">Curation snapshot</h3></div><a class="admin-link" href="{{ route('admin.genres.index') }}">Open curation →</a></div><div class="mt-5 grid grid-cols-1 divide-y divide-white/5 md:grid-cols-3 md:divide-x md:divide-y-0"><div class="py-3 md:pr-5"><p class="font-serif text-sm">Top genres</p><a class="admin-link mt-4 block" href="{{ route('admin.genres.index') }}">Manage genres →</a></div><div class="py-3 md:px-5"><p class="font-serif text-sm">Trending tags</p><a class="admin-link mt-4 block" href="{{ route('admin.tags.index') }}">Manage tags →</a></div><div class="py-3 md:pl-5"><p class="font-serif text-sm">Spotlight slider</p><a class="admin-link mt-4 block" href="{{ route('admin.carousel.index') }}">Edit order →</a></div></div></section><section class="console-card p-5 xl:col-span-4"><div class="flex items-center justify-between"><div><p class="admin-kicker">Communications</p><h3 class="admin-section-title">Announcements</h3></div><a class="admin-link" href="{{ route('admin.announcements.index') }}">Manage →</a></div><p class="mt-5 text-sm text-zinc-400">Publish updates for your readers and authors.</p><a href="{{ route('admin.announcements.create') }}" class="maintenance-link mt-5 block text-center">＋　New announcement</a></section></div>
</div>
